version: '2.0'
services:
  retriever:
    image: fideltak/rubrik-file-retriever:0.1
    environment:
      - TZ='America/Los_Angeles'
      - rubrik_cdm_node_ip=172.16.14.220
      - rubrik_cdm_username=tak
      - rubrik_cdm_password=P@ssw0rd
      - RUBRICK_TARGET_HOST=rubrik-sql01.hybrid-lab.local
      - RUBRICK_TARGET_FILESET=sdk01
      - RUBRICK_TARGET_HOSTOS=Linux
      - RUBRICK_TARGET_DATE=04-20-2020 12:02 AM
      - RUBRICK_TARGET_FILEPATH=/rubrik/bu-tar01/test01.txt
      - DOWNLOAD_FILE_PATH=/tmp/test01.txt